SimpleBuffs = SimpleBuffs or {}
local ns = SimpleBuffs

ns.TEXT = {
	EMPTY = "",
	SPACE = " ",
	PERCENT = "%",
	OPTIONS_TITLE = "Simple Buffs",
	OPTIONS_VERSION_FORMAT = "Version %s",
	OPTIONS_SUBTITLE = "Configure buff and debuff timers for supported unit frames.",
	OPTIONS_DISABLE_ALL = "Disable All",
	OPTIONS_ENABLE_ALL = "Enable All",
	OPTIONS_RESET_DEFAULTS = "Reset All Defaults",
	OPTIONS_RESET_UNIT_DEFAULTS_FORMAT = "Reset %s Defaults",
	OPTIONS_COPY_FROM = "Copy From",
	OPTIONS_COPY = "Copy",
	OPTIONS_MODE = "Mode",
	OPTIONS_STANDALONE_MOVE_HELP = "Hold Shift and left-click-drag buffs\nor debuffs to move standalone displays.",
	OPTIONS_LAYOUT = "Layout",
	OPTIONS_SORT = "Sort",
	OPTIONS_FILTER = "Filter",
	OPTIONS_AURA_FRAME_ENABLED = "Enabled",
	OPTIONS_ICON_SIZE = "Icon Size",
	OPTIONS_SPACING = "Spacing",
	OPTIONS_MAX_AURAS = "Max Auras",
	OPTIONS_SCALE = "Scale",
	OPTIONS_SHOW_COUNTDOWN = "Show Countdown Text",
	OPTIONS_SHOW_SWIPE = "Show Cooldown Swipe",
	OPTIONS_SHOW_COUNTS = "Show Stack Counts",
	OPTIONS_RESET_CONFIRM = "Reset all Simple Buffs settings to their defaults?",
	OPTIONS_TOOLTIP_MODE = "Choose whether aura displays attach to supported unit frames, appear as standalone movable groups, or show both.",
	OPTIONS_TOOLTIP_ATTACHED_POSITION = "Choose where attached aura displays sit relative to their unit frame.",
	OPTIONS_TOOLTIP_LAYOUT = "Choose the direction used to arrange aura icons within each buff or debuff row.",
	OPTIONS_TOOLTIP_SORT = "Choose how auras are ordered before they are displayed.",
	OPTIONS_TOOLTIP_FILTER = "Limit displayed auras by Blizzard aura filter categories, such as player-cast or important effects.",
	OPTIONS_TOOLTIP_AURA_FRAME_ENABLED = "Show or hide this display. Use the Buffs and Debuffs sub-tabs above to configure each type separately.",
	OPTIONS_TOOLTIP_ICON_SIZE = "Set the width and height of each buff or debuff icon.",
	OPTIONS_TOOLTIP_SPACING = "Set the empty space between aura icons in the same row.",
	OPTIONS_TOOLTIP_MAX_AURAS = "Set the maximum number of buffs or debuffs shown per unit group.",
	OPTIONS_TOOLTIP_SCALE = "Scale the standalone and attached aura displays larger or smaller.",
	OPTIONS_TOOLTIP_LOCKED = "When checked, standalone displays cannot be moved. Uncheck to move standalone displays with Shift-left-click-drag.",
	OPTIONS_TOOLTIP_RESET_UNIT_DEFAULTS = "Reset this unit tab to its default settings.",
	OPTIONS_TOOLTIP_COPY_FROM = "Choose another unit tab to copy settings from.",
	OPTIONS_TOOLTIP_COPY = "Copy all settings from the selected unit tab onto this tab.",
	AURA_TOOLTIP_FALLBACK = "Aura",
	LOCK_STATE_LOCKED = "Locked",
	LOCK_STATE_UNLOCKED = "Unlocked",
	LOADED = "Simple Buffs loaded. Use /sbuff for options.",
	RESET = "Simple Buffs settings reset.",
	LOCKED = "Simple Buffs frames locked.",
	UNLOCKED = "Simple Buffs frames unlocked. Hold Shift and drag standalone frames to move them.",
	TOOLTIP_DIVIDER = "----------------",
	STANDALONE_TOOLTIP_UNIT = "Frame: %s",
	STANDALONE_MOVE_TOOLTIP = "Hold Shift and left-click-drag to move this standalone display.",
	MINIMAP_TOOLTIP_OPEN = "Left-click to open options.",
	MINIMAP_TOOLTIP_STATE = "Dragging: %s",
	MINIMAP_TOOLTIP_LOCK = "Right-click to toggle frame dragging lock.",
	MINIMAP_TOOLTIP_DRAG = "Drag to move this button.",
	SLASH_HELP_TITLE = "Simple Buffs commands:",
	SLASH_HELP_OPEN = "/sbuff - Open options",
	SLASH_HELP_LOCK = "/sbuff lock - Lock standalone displays",
	SLASH_HELP_UNLOCK = "/sbuff unlock - Unlock Shift-drag for standalone displays",
	SLASH_HELP_RESET = "/sbuff reset - Reset settings",
}

function ns.PrintMessage(message)
	if DEFAULT_CHAT_FRAME then
		DEFAULT_CHAT_FRAME:AddMessage(message)
	else
		print(message)
	end
end
